### ISSUE TITLE
Otphelper will not launch from http://dukesrg.github.io/2xrsa.html?arm11.bin

### ISSUE THREAD

**Issue by skylinekiller** [d0k3/OTPHelper#14]
On section 3 step 1, when i input this into the browser on my 3ds, it just loads the guide page as if I am browsing the guide.  OTPhelper does not launch.

I recopied the OTP files again but same result

**Comment by al3x10m** [comment]
are you sure you're not typing the url in the google box?

**Comment by d0k3** [comment]
You're doing something wrong, otherwise this result is impossible. Check your web connection, don't put that URL into the Google search, and make sure you read the guide and do everything right. 

If that issue really persists (and I honestly doubt it will), it is an issue of the 2xrsa entrypoint:
https://github.com/b1l1s/2xrsa

Closing this for now.

**Comment by skylinekiller** [comment]
That was exactly what I was doing… I wasted 2 days on this…do I feel dumb!
