### ISSUE TITLE
More info about software option?

### ISSUE THREAD

**Issue by mariogamer2** [d0k3/OTPHelper#6]
Hello,

I don't understand a lot of part of the soft.,can you explain me and (maybe) adding it to README?

**Comment by d0k3** [comment]
You should refer to [Plailects guide](https://github.com/Plailect/Guide/wiki). If some functionality in there is not mentioned in that guiide, that's probably because it is for troubleshooting or last resort measures, meaning you should not be using it without asking the pros first.

Other than that, most of the functionality in here is a direct port from Decrypt9WIP, which actually has a pretty fine readme.
